SDRAngel: BladeRF2Output::MsgStartStop Class Reference
BladeRF2Output::MsgStartStop Class Reference
#include <bladerf2output.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 62 of file bladerf2output.h.
Constructor & Destructor Documentation
MsgStartStop()
BladeRF2Output::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 75 of file bladerf2output.h.
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* BladeRF2Output::MsgStartStop::create (bool startStop) inline static
Definition at line 68 of file bladerf2output.h.
Referenced by BladeRF2OutputGui::on_startStop_toggled(), and BladeRF2Output::webapiRun().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool BladeRF2Output::MsgStartStop::getStartStop () const inline
Definition at line 66 of file bladerf2output.h.
Referenced by BladeRF2OutputGui::handleMessage(), and BladeRF2Output::handleMessage().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool BladeRF2Output::MsgStartStop::m_startStop protected
Definition at line 73 of file bladerf2output.h.
The documentation for this class was generated from the following file:
plugins/samplesink/bladerf2output/bladerf2output.h