SDRAngel: TestMI::MsgConfigureTestSource Class Reference
TestMI::MsgConfigureTestSource Class Reference
#include <testmi.h>
Public Member Functions
const TestMISettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureTestSource * create (const TestMISettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureTestSource (const TestMISettings &settings, bool force)
Private Attributes
TestMISettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 38 of file testmi.h.
Constructor & Destructor Documentation
MsgConfigureTestSource()
TestMI::MsgConfigureTestSource::MsgConfigureTestSource (const TestMISettings & settings, bool force) inline private
Definition at line 54 of file testmi.h.
Referenced by create().
                                                                            :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureTestSource* TestMI::MsgConfigureTestSource::create (const TestMISettings & settings, bool force) inline static
Definition at line 45 of file testmi.h.
References MsgConfigureTestSource().
Referenced by TestMI::deserialize(), TestMI::setSourceCenterFrequency(), TestMIGui::updateHardware(), and TestMI::webapiSettingsPutPatch().
         {
             return new MsgConfigureTestSource(settings, force);
         }
getForce()
bool TestMI::MsgConfigureTestSource::getForce () const inline
Definition at line 43 of file testmi.h.
References m_force.
Referenced by TestMI::handleMessage().
 { return m_force; }
getSettings()
const TestMISettings& TestMI::MsgConfigureTestSource::getSettings () const inline
Definition at line 42 of file testmi.h.
References m_settings.
Referenced by TestMIGui::handleMessage(), and TestMI::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool TestMI::MsgConfigureTestSource::m_force private
Definition at line 52 of file testmi.h.
Referenced by getForce().
m_settings
TestMISettings TestMI::MsgConfigureTestSource::m_settings private
Definition at line 51 of file testmi.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/samplemimo/testmi/testmi.h