SDRAngel: DeviceUserArgsDialog Class Reference
DeviceUserArgsDialog Class Reference
#include <deviceuserargsdialog.h>
Inherits QDialog.
Classes
struct HWDeviceReference
Public Member Functions
DeviceUserArgsDialog (DeviceEnumerator *deviceEnumerator, DeviceUserArgs &hardwareDeviceUserArgs, QWidget *parent=0)
~DeviceUserArgsDialog ()
Private Slots
void accept ()
void reject ()
void on_importDevice_clicked (bool checked)
void on_deleteArgs_clicked (bool checked)
void on_argsTree_currentItemChanged (QTreeWidgetItem *currentItem, QTreeWidgetItem *previousItem)
void on_argStringEdit_editingFinished ()
Private Member Functions
void pushHWDeviceReference (const PluginInterface::SamplingDevice *samplingDevice)
void displayArgsByDevice ()
Private Attributes
Ui::DeviceUserArgsDialog * ui
DeviceEnumerator * m_deviceEnumerator
DeviceUserArgs & m_hardwareDeviceUserArgs
std::vector< HWDeviceReference > m_availableHWDevices
DeviceUserArgs m_deviceUserArgsCopy
Detailed Description
Definition at line 35 of file deviceuserargsdialog.h.
Constructor & Destructor Documentation
DeviceUserArgsDialog()
DeviceUserArgsDialog::DeviceUserArgsDialog (DeviceEnumerator * deviceEnumerator, DeviceUserArgs & hardwareDeviceUserArgs, QWidget * parent = 0) explicit
Definition at line 22 of file deviceuserargsdialog.cpp.
References arg(), displayArgsByDevice(), DeviceEnumerator::getMIMOSamplingDevice(), DeviceEnumerator::getNbMIMOSamplingDevices(), DeviceEnumerator::getNbRxSamplingDevices(), DeviceEnumerator::getNbTxSamplingDevices(), DeviceEnumerator::getRxSamplingDevice(), DeviceEnumerator::getTxSamplingDevice(), i, m_availableHWDevices, m_deviceEnumerator, pushHWDeviceReference(), and ui.
   :
     QDialog(parent),
     ui(new Ui::DeviceUserArgsDialog),
     m_deviceEnumerator(deviceEnumerator),
     m_hardwareDeviceUserArgs(hardwareDeviceUserArgs),
     m_deviceUserArgsCopy(hardwareDeviceUserArgs)
 {
     ui->setupUi(this);
     for (int i = 0; i < m_deviceEnumerator->getNbRxSamplingDevices(); i++) {
         pushHWDeviceReference(m_deviceEnumerator->getRxSamplingDevice(i));
     }
     for (int i = 0; i < m_deviceEnumerator->getNbTxSamplingDevices(); i++) {
         pushHWDeviceReference(m_deviceEnumerator->getTxSamplingDevice(i));
     }
     for (int i = 0; i < m_deviceEnumerator->getNbMIMOSamplingDevices(); i++) {
         pushHWDeviceReference(m_deviceEnumerator->getMIMOSamplingDevice(i));
     }
     for (auto& hwItem : m_availableHWDevices)
     {
         QTreeWidgetItem *treeItem = new QTreeWidgetItem(ui->deviceTree);
         treeItem->setText(0, hwItem.m_hardwareId);
         treeItem->setText(1, tr("%1").arg(hwItem.m_sequence));
         treeItem->setText(2, hwItem.m_description);
     }
     ui->deviceTree->resizeColumnToContents(0);
     ui->deviceTree->resizeColumnToContents(1);
     ui->deviceTree->resizeColumnToContents(2);
     displayArgsByDevice();
 }
~DeviceUserArgsDialog()
DeviceUserArgsDialog::~DeviceUserArgsDialog ()
Definition at line 62 of file deviceuserargsdialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
accept
void DeviceUserArgsDialog::accept () private slot
Definition at line 111 of file deviceuserargsdialog.cpp.
References m_deviceUserArgsCopy, and m_hardwareDeviceUserArgs.
 {
     m_hardwareDeviceUserArgs = m_deviceUserArgsCopy;
     QDialog::accept();
 }
displayArgsByDevice()
void DeviceUserArgsDialog::displayArgsByDevice () private
Definition at line 67 of file deviceuserargsdialog.cpp.
References arg(), DeviceUserArgs::getArgsByDevice(), m_deviceUserArgsCopy, and ui.
Referenced by DeviceUserArgsDialog(), on_argStringEdit_editingFinished(), on_deleteArgs_clicked(), and on_importDevice_clicked().
 {
     ui->argsTree->blockSignals(true);
     ui->argsTree->clear();
     ui->argStringEdit->clear();
     QList<DeviceUserArgs::Args>::const_iterator it = m_deviceUserArgsCopy.getArgsByDevice().begin();
     for (; it != m_deviceUserArgsCopy.getArgsByDevice().end(); ++it)
     {
         QTreeWidgetItem *treeItem = new QTreeWidgetItem(ui->argsTree);
         treeItem->setText(0, it->m_id);
         treeItem->setText(1, tr("%1").arg(it->m_sequence));
         treeItem->setText(2, it->m_args);
     }
     ui->argsTree->resizeColumnToContents(0);
     ui->argsTree->resizeColumnToContents(1);
     ui->argsTree->resizeColumnToContents(2);
     ui->argsTree->blockSignals(false);
 }
on_argsTree_currentItemChanged
void DeviceUserArgsDialog::on_argsTree_currentItemChanged (QTreeWidgetItem * currentItem, QTreeWidgetItem * previousItem) private slot
Definition at line 150 of file deviceuserargsdialog.cpp.
References ui.
 {
     (void) previousItem;
     ui->argStringEdit->setText(currentItem->text(2));
 }
on_argStringEdit_editingFinished
void DeviceUserArgsDialog::on_argStringEdit_editingFinished () private slot
Definition at line 156 of file deviceuserargsdialog.cpp.
References displayArgsByDevice(), m_deviceUserArgsCopy, ui, and DeviceUserArgs::updateDeviceArgs().
 {
     QTreeWidgetItem *deviceItem = ui->argsTree->currentItem();
     if (deviceItem)
     {
         bool ok;
         int sequence = deviceItem->text(1).toInt(&ok);
         m_deviceUserArgsCopy.updateDeviceArgs(deviceItem->text(0), sequence, ui->argStringEdit->text());
         displayArgsByDevice();
     }
 }
on_deleteArgs_clicked
void DeviceUserArgsDialog::on_deleteArgs_clicked (bool checked) private slot
Definition at line 136 of file deviceuserargsdialog.cpp.
References DeviceUserArgs::deleteDeviceArgs(), displayArgsByDevice(), m_deviceUserArgsCopy, and ui.
 {
     (void) checked;
     QTreeWidgetItem *deviceItem = ui->argsTree->currentItem();
     if (deviceItem)
     {
         bool ok;
         int sequence = deviceItem->text(1).toInt(&ok);
         m_deviceUserArgsCopy.deleteDeviceArgs(deviceItem->text(0), sequence);
         displayArgsByDevice();
     }
 }
on_importDevice_clicked
void DeviceUserArgsDialog::on_importDevice_clicked (bool checked) private slot
Definition at line 122 of file deviceuserargsdialog.cpp.
References DeviceUserArgs::addDeviceArgs(), displayArgsByDevice(), m_deviceUserArgsCopy, and ui.
 {
     (void) checked;
     QTreeWidgetItem *deviceItem = ui->deviceTree->currentItem();
     if (deviceItem)
     {
         bool ok;
         int sequence = deviceItem->text(1).toInt(&ok);
         m_deviceUserArgsCopy.addDeviceArgs(deviceItem->text(0), sequence, "");
         displayArgsByDevice();
     }
 }
pushHWDeviceReference()
void DeviceUserArgsDialog::pushHWDeviceReference (const PluginInterface::SamplingDevice * samplingDevice) private
Definition at line 89 of file deviceuserargsdialog.cpp.
References PluginInterface::SamplingDevice::displayedName, PluginInterface::SamplingDevice::hardwareId, m_availableHWDevices, DeviceUserArgsDialog::HWDeviceReference::m_description, DeviceUserArgsDialog::HWDeviceReference::m_hardwareId, DeviceUserArgsDialog::HWDeviceReference::m_sequence, and PluginInterface::SamplingDevice::sequence.
Referenced by DeviceUserArgsDialog().
 {
     HWDeviceReference hw;
     hw.m_hardwareId = samplingDevice->hardwareId;
     hw.m_sequence = samplingDevice->sequence;
     hw.m_description = samplingDevice->displayedName;
     bool found = false;
     for (auto& hwAvail : m_availableHWDevices)
     {
         if (hw == hwAvail)
         {
             found = true;
             break;
         }
     }
     if (!found) {
         m_availableHWDevices.push_back(hw);
     }
 }
reject
void DeviceUserArgsDialog::reject () private slot
Definition at line 117 of file deviceuserargsdialog.cpp.
 {
     QDialog::reject();
 }
Member Data Documentation
m_availableHWDevices
std::vector<HWDeviceReference> DeviceUserArgsDialog::m_availableHWDevices private
Definition at line 59 of file deviceuserargsdialog.h.
Referenced by DeviceUserArgsDialog(), and pushHWDeviceReference().
m_deviceEnumerator
DeviceEnumerator* DeviceUserArgsDialog::m_deviceEnumerator private
Definition at line 57 of file deviceuserargsdialog.h.
Referenced by DeviceUserArgsDialog().
m_deviceUserArgsCopy
DeviceUserArgs DeviceUserArgsDialog::m_deviceUserArgsCopy private
Definition at line 60 of file deviceuserargsdialog.h.
Referenced by accept(), displayArgsByDevice(), on_argStringEdit_editingFinished(), on_deleteArgs_clicked(), and on_importDevice_clicked().
m_hardwareDeviceUserArgs
DeviceUserArgs& DeviceUserArgsDialog::m_hardwareDeviceUserArgs private
Definition at line 58 of file deviceuserargsdialog.h.
Referenced by accept().
ui
Ui::DeviceUserArgsDialog* DeviceUserArgsDialog::ui private
Definition at line 56 of file deviceuserargsdialog.h.
Referenced by DeviceUserArgsDialog(), displayArgsByDevice(), on_argsTree_currentItemChanged(), on_argStringEdit_editingFinished(), on_deleteArgs_clicked(), on_importDevice_clicked(), and ~DeviceUserArgsDialog().
The documentation for this class was generated from the following files:
sdrgui/gui/deviceuserargsdialog.h
sdrgui/gui/deviceuserargsdialog.cpp