SDRAngel: HBFilterChainConverter Class Reference
HBFilterChainConverter Class Reference
#include <hbfilterchainconverter.h>
Static Public Member Functions
static double convertToIndexes (unsigned int log2, unsigned int chainHash, std::vector< unsigned int > &chainIndexes)
static double convertToString (unsigned int log2, unsigned int chainHash, QString &chainString)
static double getShiftFactor (unsigned int log2, unsigned int chainHash)
Detailed Description
Definition at line 27 of file hbfilterchainconverter.h.
Member Function Documentation
convertToIndexes()
double HBFilterChainConverter::convertToIndexes (unsigned int log2, unsigned int chainHash, std::vector< unsigned int > & chainIndexes) static
Definition at line 22 of file hbfilterchainconverter.cpp.
References i.
Referenced by DownChannelizer::applySetting(), and UpChannelizer::applySetting().
 {
     chainIndexes.clear();
     if (log2 == 0) {
         return 0.0;
     }
     unsigned int s = 1;
     unsigned int u = chainHash;
     for (unsigned int i = 0; i < log2; i++) {
         s *= 3;
     }
     u %= s; // scale
     unsigned int ix = log2;
     double shift = 0.0;
     double shift_stage = 1.0 / (1<<(log2+1));
     // base3 conversion
     do
     {
         int r = u % 3;
         chainIndexes.push_back(r);
         shift += (r-1)*shift_stage;
         shift_stage *= 2;
         u /= 3;
         ix--;
     } while (u);
     // continue shift with leading zeroes. ix has the number of leading zeroes.
     for (unsigned int i = 0; i < ix; i++)
     {
         chainIndexes.push_back(0);
         shift -= shift_stage;
         shift_stage *= 2;
     }
     return shift;
 }
convertToString()
double HBFilterChainConverter::convertToString (unsigned int log2, unsigned int chainHash, QString & chainString) static
Definition at line 64 of file hbfilterchainconverter.cpp.
References i.
Referenced by LocalSinkGUI::applyPosition(), LocalSourceGUI::applyPosition(), RemoteSinkGUI::applyPosition(), and FileSourceGUI::applyPosition().
 {
     if (log2 == 0)
     {
         chainString = "C";
         return 0.0;
     }
     unsigned int s = 1;
     unsigned int u = chainHash;
     chainString = "";
     for (unsigned int i = 0; i < log2; i++) {
         s *= 3;
     }
     u %= s; // scale
     unsigned int ix = log2;
     double shift = 0.0;
     double shift_stage = 1.0 / (1<<(log2+1));
     // base3 conversion
     do
     {
         int r = u % 3;
         if (r == 0) {
             chainString = "L" + chainString;
         } else if (r == 1) {
             chainString = "C" + chainString;
         } else if (r == 2) {
             chainString = "H" + chainString;
         }
         shift += (r-1)*shift_stage;
         shift_stage *= 2;
         u /= 3;
         ix--;
     } while (u);
     // continue shift with leading zeroes. ix has the number of leading zeroes.
     for (unsigned int i = 0; i < ix; i++)
     {
         chainString = "L" + chainString;
         shift -= shift_stage;
         shift_stage *= 2;
     }
     return shift;
 }
getShiftFactor()
double HBFilterChainConverter::getShiftFactor (unsigned int log2, unsigned int chainHash) static
Definition at line 115 of file hbfilterchainconverter.cpp.
References i.
Referenced by LocalSink::calculateFrequencyOffset(), LocalSource::calculateFrequencyOffset(), RemoteSink::calculateFrequencyOffset(), and FileSource::calculateFrequencyOffset().
 {
     if (log2 == 0)
     {
         return 0.0;
     }
     unsigned int s = 1;
     unsigned int u = chainHash;
     for (unsigned int i = 0; i < log2; i++) {
         s *= 3;
     }
     u %= s; // scale
     unsigned int ix = log2;
     double shift = 0.0;
     double shift_stage = 1.0 / (1<<(log2+1));
     // base3 conversion
     do
     {
         int r = u % 3;
         shift += (r-1)*shift_stage;
         shift_stage *= 2;
         u /= 3;
         ix--;
     } while (u);
     // continue shift with leading zeroes. ix has the number of leading zeroes.
     for (unsigned int i = 0; i < ix; i++)
     {
         shift -= shift_stage;
         shift_stage *= 2;
     }
     return shift;
 }
The documentation for this class was generated from the following files:
sdrbase/dsp/hbfilterchainconverter.h
sdrbase/dsp/hbfilterchainconverter.cpp