SDRAngel: ChannelAnalyzerGUI Class Reference
ChannelAnalyzerGUI Class Reference
#include <chanalyzergui.h>
Public Slots
void channelMarkerChangedByCursor ()
void channelMarkerHighlightedByCursor ()
Public Member Functions
virtual void destroy ()
void setName (const QString &name)
QString getName () const
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from RollupWidget
RollupWidget (QWidget *parent=NULL)
void setTitleColor (const QColor &c)
void setHighlighted (bool highlighted)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Static Public Member Functions
static ChannelAnalyzerGUI * create (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
Private Slots
void on_deltaFrequency_changed (qint64 value)
void on_channelSampleRate_changed (quint64 value)
void on_pll_toggled (bool checked)
void on_pllPskOrder_currentIndexChanged (int index)
void on_useRationalDownsampler_toggled (bool checked)
void on_signalSelect_currentIndexChanged (int index)
void on_rrcFilter_toggled (bool checked)
void on_rrcRolloff_valueChanged (int value)
void on_BW_valueChanged (int value)
void on_lowCut_valueChanged (int value)
void on_spanLog2_currentIndexChanged (int index)
void on_ssb_toggled (bool checked)
void onWidgetRolled (QWidget *widget, bool rollDown)
void onMenuDialogCalled (const QPoint &p)
void handleInputMessages ()
void tick ()
Private Member Functions
ChannelAnalyzerGUI (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel, QWidget *parent=0)
virtual ~ChannelAnalyzerGUI ()
int getRequestedChannelSampleRate ()
void setNewFinalRate ()
set sample rate after final in-channel decimation
void setFiltersUIBoundaries ()
void blockApplySettings (bool block)
void applySettings (bool force=false)
void displaySettings ()
void displayPLLSettings ()
void setSpectrumDisplay ()
void leaveEvent (QEvent *)
void enterEvent (QEvent *)
Private Attributes
Ui::ChannelAnalyzerGUI * ui
PluginAPI * m_pluginAPI
DeviceUISet * m_deviceUISet
ChannelMarker m_channelMarker
ChannelAnalyzerSettings m_settings
bool m_doApplySettings
int m_rate
sample rate after final in-channel decimation (spanlog2)
MovingAverageUtil< double, double, 40 > m_channelPowerAvg
ChannelAnalyzer * m_channelAnalyzer
SpectrumScopeComboVis * m_spectrumScopeComboVis
SpectrumVis * m_spectrumVis
ScopeVis * m_scopeVis
MessageQueue m_inputMessageQueue
Additional Inherited Members
Signals inherited from RollupWidget
void widgetRolled (QWidget *widget, bool rollDown)
Protected Types inherited from RollupWidget
enum { VersionMarker = 0xff }
enum ContextMenuType { ContextMenuNone, ContextMenuChannelSettings, ContextMenuStreamSettings }
Protected Member Functions inherited from RollupWidget
int arrangeRollups ()
QByteArray saveState (int version=0) const
bool restoreState (const QByteArray &state, int version=0)
void paintEvent (QPaintEvent *)
int paintRollup (QWidget *rollup, int pos, QPainter *p, bool last, const QColor &frame)
void resizeEvent (QResizeEvent *size)
void mousePressEvent (QMouseEvent *event)
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
void resetContextMenuType ()
void setStreamIndicator (const QString &indicator)
Protected Attributes inherited from RollupWidget
QColor m_titleColor
QColor m_titleTextColor
bool m_highlighted
ContextMenuType m_contextMenuType
QString m_streamIndicator
Detailed Description
Definition at line 42 of file chanalyzergui.h.
Constructor & Destructor Documentation
ChannelAnalyzerGUI()
ChannelAnalyzerGUI::ChannelAnalyzerGUI (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel, QWidget * parent = 0) explicit private
Definition at line 387 of file chanalyzergui.cpp.
References DeviceUISet::addChannelMarker(), DeviceUISet::addRollupWidget(), applySettings(), arg(), channelMarkerChangedByCursor(), channelMarkerHighlightedByCursor(), displaySettings(), ChannelMarker::getColor(), getInputMessageQueue(), BasebandSampleSink::getInputMessageQueue(), MainWindow::getInstance(), ColorMapper::GrayGold, ColorMapper::GrayGreenYellow, handleInputMessages(), m_channelAnalyzer, ChannelAnalyzer::m_channelIdURI, m_channelMarker, m_deviceUISet, m_rate, m_scopeVis, m_settings, m_spectrumScopeComboVis, m_spectrumVis, onMenuDialogCalled(), onWidgetRolled(), DeviceUISet::registerRxChannelInstance(), SDR_RX_SCALEF, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ChannelAnalyzerSettings::setChannelMarker(), ChannelMarker::setColor(), BasebandSampleSink::setMessageQueueToGUI(), ChannelAnalyzer::setSampleSink(), ChannelAnalyzerSettings::setScopeGUI(), ChannelMarker::setSidebands(), ChannelAnalyzerSettings::setSpectrumGUI(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), ChannelMarker::setVisible(), tick(), ui, ChannelMarker::usb, and RollupWidget::widgetRolled().
Referenced by create().
                                                                                                                                      :
     RollupWidget(parent),
     ui(new Ui::ChannelAnalyzerGUI),
     m_pluginAPI(pluginAPI),
     m_deviceUISet(deviceUISet),
     m_channelMarker(this),
     m_doApplySettings(true),
     m_rate(48000)
 {
     ui->setupUi(this);
     setAttribute(Qt::WA_DeleteOnClose, true);
     connect(this, SIGNAL(widgetRolled(QWidget*,bool)), this, SLOT(onWidgetRolled(QWidget*,bool)));
     connect(this, SIGNAL(customContextMenuRequested(const QPoint &)), this, SLOT(onMenuDialogCalled(const QPoint &)));
     m_spectrumVis = new SpectrumVis(SDR_RX_SCALEF, ui->glSpectrum);
     m_scopeVis = new ScopeVis(ui->glScope);
     m_spectrumScopeComboVis = new SpectrumScopeComboVis(m_spectrumVis, m_scopeVis);
     m_channelAnalyzer = (ChannelAnalyzer*) rxChannel; //new ChannelAnalyzer(m_deviceUISet->m_deviceSourceAPI);
     m_channelAnalyzer->setSampleSink(m_spectrumScopeComboVis);
     m_channelAnalyzer->setMessageQueueToGUI(getInputMessageQueue());
     ui->deltaFrequencyLabel->setText(QString("%1f").arg(QChar(0x94, 0x03)));
     ui->deltaFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->deltaFrequency->setValueRange(false, 7, -9999999, 9999999);
     ui->channelSampleRate->setColorMapper(ColorMapper(ColorMapper::GrayGreenYellow));
     ui->channelSampleRate->setValueRange(7, 0.501*m_rate, m_rate);
     ui->glSpectrum->setCenterFrequency(m_rate/2);
     ui->glSpectrum->setSampleRate(m_rate);
     ui->glSpectrum->setDisplayWaterfall(true);
     ui->glSpectrum->setDisplayMaxHold(true);
     ui->glSpectrum->setSsbSpectrum(false);
     ui->glSpectrum->setLsbDisplay(false);
     ui->glSpectrum->connectTimer(MainWindow::getInstance()->getMasterTimer());
     ui->glScope->connectTimer(MainWindow::getInstance()->getMasterTimer());
     connect(&MainWindow::getInstance()->getMasterTimer(), SIGNAL(timeout()), this, SLOT(tick()));
     m_channelMarker.blockSignals(true);
     m_channelMarker.setColor(Qt::gray);
     m_channelMarker.setBandwidth(m_rate);
     m_channelMarker.setSidebands(ChannelMarker::usb);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.setTitle("Channel Analyzer");
     m_channelMarker.blockSignals(false);
     m_channelMarker.setVisible(true); // activate signal on the last setting only
     setTitleColor(m_channelMarker.getColor());
     m_deviceUISet->registerRxChannelInstance(ChannelAnalyzer::m_channelIdURI, this);
     m_deviceUISet->addChannelMarker(&m_channelMarker);
     m_deviceUISet->addRollupWidget(this);
     ui->spectrumGUI->setBuddies(m_spectrumVis->getInputMessageQueue(), m_spectrumVis, ui->glSpectrum);
     ui->scopeGUI->setBuddies(m_scopeVis->getInputMessageQueue(), m_scopeVis, ui->glScope);
     m_settings.setChannelMarker(&m_channelMarker);
     m_settings.setSpectrumGUI(ui->spectrumGUI);
     m_settings.setScopeGUI(ui->scopeGUI);
     connect(&m_channelMarker, SIGNAL(changedByCursor()), this, SLOT(channelMarkerChangedByCursor()));
     connect(&m_channelMarker, SIGNAL(highlightedByCursor()), this, SLOT(channelMarkerHighlightedByCursor()));
     connect(getInputMessageQueue(), SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()));
     displaySettings();
     applySettings(true);
 }
~ChannelAnalyzerGUI()
ChannelAnalyzerGUI::~ChannelAnalyzerGUI () private virtual
Definition at line 455 of file chanalyzergui.cpp.
References m_channelAnalyzer, m_deviceUISet, m_scopeVis, m_spectrumScopeComboVis, m_spectrumVis, DeviceUISet::removeRxChannelInstance(), and ui.
 {
     m_deviceUISet->removeRxChannelInstance(this);
     delete m_channelAnalyzer; // TODO: check this: when the GUI closes it has to delete the demodulator
     delete m_spectrumVis;
     delete m_scopeVis;
     delete m_spectrumScopeComboVis;
     delete ui;
 }
Member Function Documentation
applySettings()
void ChannelAnalyzerGUI::applySettings (bool force = false) private
Definition at line 546 of file chanalyzergui.cpp.
References ChannelAnalyzer::MsgConfigureChannelAnalyzer::create(), ChannelAnalyzer::MsgConfigureChannelizer::create(), ChannelMarker::getCenterFrequency(), BasebandSampleSink::getInputMessageQueue(), getRequestedChannelSampleRate(), m_channelAnalyzer, m_channelMarker, m_doApplySettings, m_scopeVis, m_settings, ChannelAnalyzerSettings::m_spanLog2, MessageQueue::push(), and ScopeVis::setLiveRateLog2Decim().
Referenced by ChannelAnalyzerGUI(), channelMarkerChangedByCursor(), deserialize(), on_BW_valueChanged(), on_channelSampleRate_changed(), on_deltaFrequency_changed(), on_lowCut_valueChanged(), on_pll_toggled(), on_pllPskOrder_currentIndexChanged(), on_rrcFilter_toggled(), on_rrcRolloff_valueChanged(), on_signalSelect_currentIndexChanged(), on_spanLog2_currentIndexChanged(), on_ssb_toggled(), on_useRationalDownsampler_toggled(), onMenuDialogCalled(), and setCenterFrequency().
 {
     if (m_doApplySettings)
     {
         int sampleRate = getRequestedChannelSampleRate();
         ChannelAnalyzer::MsgConfigureChannelizer *msgChannelizer =
                 ChannelAnalyzer::MsgConfigureChannelizer::create(sampleRate, m_channelMarker.getCenterFrequency());
         m_channelAnalyzer->getInputMessageQueue()->push(msgChannelizer);
         ChannelAnalyzer::MsgConfigureChannelAnalyzer* message =
                 ChannelAnalyzer::MsgConfigureChannelAnalyzer::create( m_settings, force);
         m_channelAnalyzer->getInputMessageQueue()->push(message);
         m_scopeVis->setLiveRateLog2Decim(m_settings.m_spanLog2);
     }
 }
blockApplySettings()
void ChannelAnalyzerGUI::blockApplySettings (bool block) private
Definition at line 539 of file chanalyzergui.cpp.
References m_doApplySettings, and ui.
Referenced by displaySettings().
 {
     ui->glScope->blockSignals(block);
     ui->glSpectrum->blockSignals(block);
     m_doApplySettings = !block;
 }
channelMarkerChangedByCursor
void ChannelAnalyzerGUI::channelMarkerChangedByCursor () slot
Definition at line 218 of file chanalyzergui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, and ui.
Referenced by ChannelAnalyzerGUI().
 {
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     applySettings();
 }
channelMarkerHighlightedByCursor
void ChannelAnalyzerGUI::channelMarkerHighlightedByCursor () slot
Definition at line 224 of file chanalyzergui.cpp.
References ChannelMarker::getHighlighted(), m_channelMarker, and RollupWidget::setHighlighted().
Referenced by ChannelAnalyzerGUI().
 {
     setHighlighted(m_channelMarker.getHighlighted());
 }
create()
ChannelAnalyzerGUI * ChannelAnalyzerGUI::create (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel) static
Definition at line 39 of file chanalyzergui.cpp.
References ChannelAnalyzerGUI().
Referenced by ChannelAnalyzerPlugin::createRxChannelGUI().
 {
     ChannelAnalyzerGUI* gui = new ChannelAnalyzerGUI(pluginAPI, deviceUISet, rxChannel);
     return gui;
 }
deserialize()
bool ChannelAnalyzerGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 170 of file chanalyzergui.cpp.
References applySettings(), ChannelAnalyzerSettings::deserialize(), displaySettings(), m_settings, and ChannelAnalyzerSettings::resetToDefaults().
 {
     if(m_settings.deserialize(data))
     {
         displaySettings();
         applySettings(true); // will have true
         return true;
     }
     else
     {
         m_settings.resetToDefaults();
         displaySettings();
         applySettings(true); // will have true
         return false;
     }
 }
destroy()
void ChannelAnalyzerGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 45 of file chanalyzergui.cpp.
 {
     delete this;
 }
displayPLLSettings()
void ChannelAnalyzerGUI::displayPLLSettings () private
Definition at line 130 of file chanalyzergui.cpp.
References i, ChannelAnalyzerSettings::m_fll, ChannelAnalyzerSettings::m_pll, ChannelAnalyzerSettings::m_pllPskOrder, m_settings, and ui.
Referenced by displaySettings().
 {
     if (m_settings.m_fll)
     {
         ui->pllPskOrder->setCurrentIndex(5);
     }
     else
     {
         int i = 0;
         for(; ((m_settings.m_pllPskOrder>>i) & 1) == 0; i++);
         ui->pllPskOrder->setCurrentIndex(i);
     }
     ui->pll->setChecked(m_settings.m_pll);
 }
displaySettings()
void ChannelAnalyzerGUI::displaySettings () private
Definition at line 77 of file chanalyzergui.cpp.
References blockApplySettings(), displayPLLSettings(), ChannelMarker::dsb, ChannelAnalyzer::getInputSampleRate(), ChannelMarker::getTitle(), ChannelMarker::lsb, ChannelAnalyzerSettings::m_bandwidth, m_channelAnalyzer, m_channelMarker, ChannelAnalyzerSettings::m_downSample, ChannelAnalyzerSettings::m_downSampleRate, ChannelAnalyzerSettings::m_frequency, ChannelAnalyzerSettings::m_inputType, ChannelAnalyzerSettings::m_lowCutoff, ChannelAnalyzerSettings::m_rgbColor, ChannelAnalyzerSettings::m_rrc, ChannelAnalyzerSettings::m_rrcRolloff, m_settings, ChannelAnalyzerSettings::m_spanLog2, ChannelAnalyzerSettings::m_ssb, ChannelAnalyzerSettings::m_title, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ChannelMarker::setColor(), ChannelMarker::setLowCutoff(), setNewFinalRate(), ChannelMarker::setSidebands(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), ui, and ChannelMarker::usb.
Referenced by ChannelAnalyzerGUI(), and deserialize().
 {
     m_channelMarker.blockSignals(true);
     m_channelMarker.setCenterFrequency(m_settings.m_frequency);
     m_channelMarker.setBandwidth(m_settings.m_bandwidth * 2);
     m_channelMarker.setTitle(m_settings.m_title);
     m_channelMarker.setLowCutoff(m_settings.m_lowCutoff);
     if (m_settings.m_ssb)
     {
         if (m_settings.m_bandwidth < 0) {
             m_channelMarker.setSidebands(ChannelMarker::lsb);
         } else {
             m_channelMarker.setSidebands(ChannelMarker::usb);
         }
     }
     else
     {
         m_channelMarker.setSidebands(ChannelMarker::dsb);
     }
     m_channelMarker.blockSignals(false);
     m_channelMarker.setColor(m_settings.m_rgbColor); // activate signal on the last setting only
     setTitleColor(m_settings.m_rgbColor);
     setWindowTitle(m_channelMarker.getTitle());
     ui->channelSampleRate->setValueRange(7, 0.501*m_channelAnalyzer->getInputSampleRate(), m_channelAnalyzer->getInputSampleRate());
     ui->channelSampleRate->setValue(m_settings.m_downSampleRate);
     blockApplySettings(true);
     ui->useRationalDownsampler->setChecked(m_settings.m_downSample);
     setNewFinalRate();
     if (m_settings.m_ssb) {
         ui->BWLabel->setText("LP");
     } else {
         ui->BWLabel->setText("BP");
     }
     ui->ssb->setChecked(m_settings.m_ssb);
     ui->BW->setValue(m_settings.m_bandwidth/100);
     ui->lowCut->setValue(m_settings.m_lowCutoff/100);
     ui->deltaFrequency->setValue(m_settings.m_frequency);
     ui->spanLog2->setCurrentIndex(m_settings.m_spanLog2);
     displayPLLSettings();
     ui->signalSelect->setCurrentIndex((int) m_settings.m_inputType);
     ui->rrcFilter->setChecked(m_settings.m_rrc);
     QString rolloffStr = QString::number(m_settings.m_rrcRolloff/100.0, 'f', 2);
     ui->rrcRolloffText->setText(rolloffStr);
     blockApplySettings(false);
 }
enterEvent()
void ChannelAnalyzerGUI::enterEvent (QEvent *) private
Definition at line 569 of file chanalyzergui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(true);
 }
getCenterFrequency()
qint64 ChannelAnalyzerGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 60 of file chanalyzergui.cpp.
References ChannelMarker::getCenterFrequency(), and m_channelMarker.
 {
     return m_channelMarker.getCenterFrequency();
 }
getInputMessageQueue()
virtual MessageQueue* ChannelAnalyzerGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 57 of file chanalyzergui.h.
Referenced by ChannelAnalyzerGUI(), and handleInputMessages().
 { return &m_inputMessageQueue; }
getName()
QString ChannelAnalyzerGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 55 of file chanalyzergui.cpp.
 {
     return objectName();
 }
getRequestedChannelSampleRate()
int ChannelAnalyzerGUI::getRequestedChannelSampleRate () private
Definition at line 283 of file chanalyzergui.cpp.
References ChannelAnalyzer::getChannelizer(), DownChannelizer::getInputSampleRate(), m_channelAnalyzer, and ui.
Referenced by applySettings(), and setNewFinalRate().
 {
     if (ui->useRationalDownsampler->isChecked()) {
         return ui->channelSampleRate->getValueNew();
     } else {
         return m_channelAnalyzer->getChannelizer()->getInputSampleRate();
     }
 }
handleInputMessages
void ChannelAnalyzerGUI::handleInputMessages () private slot
Definition at line 203 of file chanalyzergui.cpp.
References Message::getIdentifier(), getInputMessageQueue(), and handleMessage().
Referenced by ChannelAnalyzerGUI().
 {
     Message* message;
     while ((message = getInputMessageQueue()->pop()) != 0)
     {
         qDebug("ChannelAnalyzerGUI::handleInputMessages: message: %s", message->getIdentifier());
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
handleMessage()
bool ChannelAnalyzerGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 187 of file chanalyzergui.cpp.
References ChannelAnalyzer::getInputSampleRate(), m_channelAnalyzer, ChannelAnalyzerSettings::m_downSampleRate, m_settings, Message::match(), setNewFinalRate(), and ui.
Referenced by handleInputMessages().
 {
     if (ChannelAnalyzer::MsgReportChannelSampleRateChanged::match(message))
     {
         qDebug() << "ChannelAnalyzerGUI::handleMessage: MsgReportChannelSampleRateChanged:" << m_channelAnalyzer->getInputSampleRate();
         ui->channelSampleRate->setValueRange(7, 0.501*m_channelAnalyzer->getInputSampleRate(), m_channelAnalyzer->getInputSampleRate());
         ui->channelSampleRate->setValue(m_settings.m_downSampleRate);
         m_settings.m_downSampleRate = ui->channelSampleRate->getValueNew();
         setNewFinalRate();
         return true;
     }
     return false;
 }
leaveEvent()
void ChannelAnalyzerGUI::leaveEvent (QEvent *) private
Definition at line 564 of file chanalyzergui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(false);
 }
on_BW_valueChanged
void ChannelAnalyzerGUI::on_BW_valueChanged (int value) private slot
Definition at line 319 of file chanalyzergui.cpp.
References applySettings(), ChannelAnalyzerSettings::m_bandwidth, ChannelAnalyzerSettings::m_lowCutoff, m_settings, setFiltersUIBoundaries(), and ui.
 {
     (void) value;
     setFiltersUIBoundaries();
     m_settings.m_bandwidth = ui->BW->value() * 100;
     m_settings.m_lowCutoff = ui->lowCut->value() * 100;
     applySettings();
 }
on_channelSampleRate_changed
void ChannelAnalyzerGUI::on_channelSampleRate_changed (quint64 value) private slot
Definition at line 249 of file chanalyzergui.cpp.
References applySettings(), ChannelAnalyzerSettings::m_downSampleRate, m_settings, and setNewFinalRate().
 {
     m_settings.m_downSampleRate = value;
     setNewFinalRate();
     applySettings();
 }
on_deltaFrequency_changed
void ChannelAnalyzerGUI::on_deltaFrequency_changed (qint64 value) private slot
Definition at line 298 of file chanalyzergui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, ChannelAnalyzerSettings::m_frequency, m_settings, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(value);
     m_settings.m_frequency = m_channelMarker.getCenterFrequency();
     applySettings();
 }
on_lowCut_valueChanged
void ChannelAnalyzerGUI::on_lowCut_valueChanged (int value) private slot
Definition at line 328 of file chanalyzergui.cpp.
References applySettings(), ChannelAnalyzerSettings::m_bandwidth, ChannelAnalyzerSettings::m_lowCutoff, m_settings, setFiltersUIBoundaries(), and ui.
 {
     (void) value;
     setFiltersUIBoundaries();
     m_settings.m_bandwidth = ui->BW->value() * 100;
     m_settings.m_lowCutoff = ui->lowCut->value() * 100;
     applySettings();
 }
on_pll_toggled
void ChannelAnalyzerGUI::on_pll_toggled (bool checked) private slot
Definition at line 256 of file chanalyzergui.cpp.
References applySettings(), ChannelAnalyzerSettings::m_pll, m_settings, and ui.
 {
     if (!checked) {
         ui->pll->setToolTip(tr("PLL lock"));
     }
     m_settings.m_pll = checked;
     applySettings();
 }
on_pllPskOrder_currentIndexChanged
void ChannelAnalyzerGUI::on_pllPskOrder_currentIndexChanged (int index) private slot
Definition at line 266 of file chanalyzergui.cpp.
References applySettings(), ChannelAnalyzerSettings::m_fll, ChannelAnalyzerSettings::m_pllPskOrder, and m_settings.
 {
     if (index < 5) {
         m_settings.m_pllPskOrder = (1<<index);
     }
     m_settings.m_fll = (index == 5);
     applySettings();
 }
on_rrcFilter_toggled
void ChannelAnalyzerGUI::on_rrcFilter_toggled (bool checked) private slot
Definition at line 305 of file chanalyzergui.cpp.
References applySettings(), ChannelAnalyzerSettings::m_rrc, and m_settings.
 {
     m_settings.m_rrc = checked;
     applySettings();
 }
on_rrcRolloff_valueChanged
void ChannelAnalyzerGUI::on_rrcRolloff_valueChanged (int value) private slot
Definition at line 311 of file chanalyzergui.cpp.
References applySettings(), ChannelAnalyzerSettings::m_rrcRolloff, m_settings, and ui.
 {
     m_settings.m_rrcRolloff = value;
     QString rolloffStr = QString::number(value/100.0, 'f', 2);
     ui->rrcRolloffText->setText(rolloffStr);
     applySettings();
 }
on_signalSelect_currentIndexChanged
void ChannelAnalyzerGUI::on_signalSelect_currentIndexChanged (int index) private slot
Definition at line 292 of file chanalyzergui.cpp.
References applySettings(), ChannelAnalyzerSettings::m_inputType, and m_settings.
 {
     m_settings.m_inputType = (ChannelAnalyzerSettings::InputType) index;
     applySettings();
 }
on_spanLog2_currentIndexChanged
void ChannelAnalyzerGUI::on_spanLog2_currentIndexChanged (int index) private slot
Definition at line 337 of file chanalyzergui.cpp.
References applySettings(), m_settings, ChannelAnalyzerSettings::m_spanLog2, and setNewFinalRate().
 {
     if ((index < 0) || (index > 6)) {
         return;
     }
     m_settings.m_spanLog2 = index;
     setNewFinalRate();
     applySettings();
 }
on_ssb_toggled
void ChannelAnalyzerGUI::on_ssb_toggled (bool checked) private slot
Definition at line 348 of file chanalyzergui.cpp.
References applySettings(), m_settings, ChannelAnalyzerSettings::m_ssb, setFiltersUIBoundaries(), and ui.
 {
     m_settings.m_ssb = checked;
     if (checked) {
         ui->BWLabel->setText("LP");
     } else {
         ui->BWLabel->setText("BP");
     }
     setFiltersUIBoundaries();
     applySettings();
 }
on_useRationalDownsampler_toggled
void ChannelAnalyzerGUI::on_useRationalDownsampler_toggled (bool checked) private slot
Definition at line 276 of file chanalyzergui.cpp.
References applySettings(), ChannelAnalyzerSettings::m_downSample, m_settings, and setNewFinalRate().
 {
     m_settings.m_downSample = checked;
     setNewFinalRate();
     applySettings();
 }
onMenuDialogCalled
void ChannelAnalyzerGUI::onMenuDialogCalled (const QPoint & p) private slot
Definition at line 366 of file chanalyzergui.cpp.
References applySettings(), RollupWidget::ContextMenuChannelSettings, ChannelMarker::getCenterFrequency(), ChannelMarker::getColor(), ChannelMarker::getTitle(), m_channelMarker, RollupWidget::m_contextMenuType, ChannelAnalyzerSettings::m_frequency, ChannelAnalyzerSettings::m_rgbColor, m_settings, ChannelAnalyzerSettings::m_title, RollupWidget::resetContextMenuType(), and RollupWidget::setTitleColor().
Referenced by ChannelAnalyzerGUI().
 {
     if (m_contextMenuType == ContextMenuChannelSettings)
     {
         BasicChannelSettingsDialog dialog(&m_channelMarker, this);
         dialog.move(p);
         dialog.exec();
         m_settings.m_frequency = m_channelMarker.getCenterFrequency();
         m_settings.m_rgbColor = m_channelMarker.getColor().rgb();
         m_settings.m_title = m_channelMarker.getTitle();
         setWindowTitle(m_settings.m_title);
         setTitleColor(m_settings.m_rgbColor);
         applySettings();
     }
     resetContextMenuType();
 }
onWidgetRolled
void ChannelAnalyzerGUI::onWidgetRolled (QWidget * widget, bool rollDown) private slot
Definition at line 360 of file chanalyzergui.cpp.
Referenced by ChannelAnalyzerGUI().
 {
     (void) widget;
     (void) rollDown;
 }
resetToDefaults()
void ChannelAnalyzerGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 72 of file chanalyzergui.cpp.
References m_settings, and ChannelAnalyzerSettings::resetToDefaults().
 {
     m_settings.resetToDefaults();
 }
serialize()
QByteArray ChannelAnalyzerGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 165 of file chanalyzergui.cpp.
References m_settings, and ChannelAnalyzerSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void ChannelAnalyzerGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 65 of file chanalyzergui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, ChannelAnalyzerSettings::m_frequency, m_settings, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(centerFrequency);
     m_settings.m_frequency = m_channelMarker.getCenterFrequency();
     applySettings();
 }
setFiltersUIBoundaries()
void ChannelAnalyzerGUI::setFiltersUIBoundaries () private
Definition at line 481 of file chanalyzergui.cpp.
References arg(), ChannelMarker::dsb, ChannelMarker::lsb, m_channelMarker, m_rate, ChannelMarker::setBandwidth(), ChannelMarker::setLowCutoff(), ChannelMarker::setSidebands(), setSpectrumDisplay(), ui, and ChannelMarker::usb.
Referenced by on_BW_valueChanged(), on_lowCut_valueChanged(), on_ssb_toggled(), and setNewFinalRate().
 {
     bool dsb = !ui->ssb->isChecked();
     int bw = ui->BW->value();
     int lw = ui->lowCut->value();
     int bwMax = m_rate / 200;
     bw = bw < -bwMax ? -bwMax : bw > bwMax ? bwMax : bw;
     if (bw < 0) {
         lw = lw < bw+1 ? bw+1 : lw < 0 ? lw : 0;
     } else if (bw > 0) {
         lw = lw > bw-1 ? bw-1 : lw < 0 ? 0 : lw;
     } else {
         lw = 0;
     }
     if (dsb)
     {
         bw = bw < 0 ? -bw : bw;
         lw = 0;
     }
     QString bwStr = QString::number(bw/10.0, 'f', 1);
     QString lwStr = QString::number(lw/10.0, 'f', 1);
     if (dsb) {
         ui->BWText->setText(tr("%1%2k").arg(QChar(0xB1, 0x00)).arg(bwStr));
     } else {
         ui->BWText->setText(tr("%1k").arg(bwStr));
     }
     ui->lowCutText->setText(tr("%1k").arg(lwStr));
     ui->BW->blockSignals(true);
     ui->lowCut->blockSignals(true);
     ui->BW->setMaximum(bwMax);
     ui->BW->setMinimum(dsb ? 0 : -bwMax);
     ui->BW->setValue(bw);
     ui->lowCut->setMaximum(dsb ? 0 :  bw);
     ui->lowCut->setMinimum(dsb ? 0 : -bw);
     ui->lowCut->setValue(lw);
     ui->lowCut->blockSignals(false);
     ui->BW->blockSignals(false);
     setSpectrumDisplay();
     m_channelMarker.setBandwidth(bw * 200);
     m_channelMarker.setSidebands(dsb ? ChannelMarker::dsb : bw < 0 ? ChannelMarker::lsb : ChannelMarker::usb);
     if (!dsb) {
         m_channelMarker.setLowCutoff(lw * 100);
     }
 }
setName()
void ChannelAnalyzerGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 50 of file chanalyzergui.cpp.
 {
     setObjectName(name);
 }
setNewFinalRate()
void ChannelAnalyzerGUI::setNewFinalRate () private
set sample rate after final in-channel decimation
Definition at line 465 of file chanalyzergui.cpp.
References arg(), getRequestedChannelSampleRate(), m_rate, m_scopeVis, m_settings, ChannelAnalyzerSettings::m_spanLog2, setFiltersUIBoundaries(), ScopeVis::setLiveRate(), and ui.
Referenced by displaySettings(), handleMessage(), on_channelSampleRate_changed(), on_spanLog2_currentIndexChanged(), and on_useRationalDownsampler_toggled().
 {
     m_rate = getRequestedChannelSampleRate() / (1<<m_settings.m_spanLog2);
     if (m_rate == 0) {
         m_rate = 48000;
     }
     qDebug("ChannelAnalyzerGUI::setNewFinalRate: %d m_spanLog2: %d", m_rate, m_settings.m_spanLog2);
     setFiltersUIBoundaries();
     QString s = QString::number(m_rate/1000.0, 'f', 1);
     ui->spanText->setText(tr("%1 kS/s").arg(s));
     m_scopeVis->setLiveRate(getRequestedChannelSampleRate());
 }
setSpectrumDisplay()
void ChannelAnalyzerGUI::setSpectrumDisplay () private
Definition at line 146 of file chanalyzergui.cpp.
References m_rate, m_settings, ChannelAnalyzerSettings::m_ssb, and ui.
Referenced by setFiltersUIBoundaries().
 {
     qDebug("ChannelAnalyzerGUI::setSpectrumDisplay: m_rate: %d", m_rate);
     if (m_settings.m_ssb)
     {
         ui->glSpectrum->setCenterFrequency(m_rate/4);
         ui->glSpectrum->setSampleRate(m_rate/2);
         ui->glSpectrum->setSsbSpectrum(true);
         ui->glSpectrum->setLsbDisplay(ui->BW->value() < 0);
     }
     else
     {
         ui->glSpectrum->setCenterFrequency(0);
         ui->glSpectrum->setSampleRate(m_rate);
         ui->glSpectrum->setSsbSpectrum(false);
         ui->glSpectrum->setLsbDisplay(false);
     }
 }
tick
void ChannelAnalyzerGUI::tick () private slot
Definition at line 229 of file chanalyzergui.cpp.
References arg(), CalcDb::dbPower(), ChannelAnalyzer::getChannelSampleRate(), ChannelAnalyzer::getDecimation(), ChannelAnalyzer::getMagSqAvg(), ChannelAnalyzer::getPllFrequency(), ChannelAnalyzer::isPllLocked(), m_channelAnalyzer, m_channelPowerAvg, M_PI, and ui.
Referenced by ChannelAnalyzerGUI().
 {
     m_channelPowerAvg(m_channelAnalyzer->getMagSqAvg());
     double powDb = CalcDb::dbPower((double) m_channelPowerAvg);
     ui->channelPower->setText(tr("%1 dB").arg(powDb, 0, 'f', 1));
     if (m_channelAnalyzer->isPllLocked()) {
         ui->pll->setStyleSheet("QToolButton { background-color : green; }");
     } else {
         ui->pll->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
     if (ui->pll->isChecked())
     {
         double sampleRate = ((double) m_channelAnalyzer->getChannelSampleRate()) / m_channelAnalyzer->getDecimation();
         int freq = (m_channelAnalyzer->getPllFrequency() * sampleRate) / (2.0*M_PI);
         ui->pll->setToolTip(tr("PLL lock. Freq = %1 Hz").arg(freq));
     }
 }
Member Data Documentation
m_channelAnalyzer
ChannelAnalyzer* ChannelAnalyzerGUI::m_channelAnalyzer private
Definition at line 74 of file chanalyzergui.h.
Referenced by applySettings(), ChannelAnalyzerGUI(), displaySettings(), getRequestedChannelSampleRate(), handleMessage(), tick(), and ~ChannelAnalyzerGUI().
m_channelMarker
ChannelMarker ChannelAnalyzerGUI::m_channelMarker private
Definition at line 68 of file chanalyzergui.h.
Referenced by applySettings(), ChannelAnalyzerGUI(), channelMarkerChangedByCursor(), channelMarkerHighlightedByCursor(), displaySettings(), enterEvent(), getCenterFrequency(), leaveEvent(), on_deltaFrequency_changed(), onMenuDialogCalled(), setCenterFrequency(), and setFiltersUIBoundaries().
m_channelPowerAvg
MovingAverageUtil<double, double, 40> ChannelAnalyzerGUI::m_channelPowerAvg private
Definition at line 72 of file chanalyzergui.h.
Referenced by tick().
m_deviceUISet
DeviceUISet* ChannelAnalyzerGUI::m_deviceUISet private
Definition at line 67 of file chanalyzergui.h.
Referenced by ChannelAnalyzerGUI(), and ~ChannelAnalyzerGUI().
m_doApplySettings
bool ChannelAnalyzerGUI::m_doApplySettings private
Definition at line 70 of file chanalyzergui.h.
Referenced by applySettings(), and blockApplySettings().
m_inputMessageQueue
MessageQueue ChannelAnalyzerGUI::m_inputMessageQueue private
Definition at line 78 of file chanalyzergui.h.
m_pluginAPI
PluginAPI* ChannelAnalyzerGUI::m_pluginAPI private
Definition at line 66 of file chanalyzergui.h.
m_rate
int ChannelAnalyzerGUI::m_rate private
sample rate after final in-channel decimation (spanlog2)
Definition at line 71 of file chanalyzergui.h.
Referenced by ChannelAnalyzerGUI(), setFiltersUIBoundaries(), setNewFinalRate(), and setSpectrumDisplay().
m_scopeVis
ScopeVis* ChannelAnalyzerGUI::m_scopeVis private
Definition at line 77 of file chanalyzergui.h.
Referenced by applySettings(), ChannelAnalyzerGUI(), setNewFinalRate(), and ~ChannelAnalyzerGUI().
m_settings
ChannelAnalyzerSettings ChannelAnalyzerGUI::m_settings private
Definition at line 69 of file chanalyzergui.h.
Referenced by applySettings(), ChannelAnalyzerGUI(), deserialize(), displayPLLSettings(), displaySettings(), handleMessage(), on_BW_valueChanged(), on_channelSampleRate_changed(), on_deltaFrequency_changed(), on_lowCut_valueChanged(), on_pll_toggled(), on_pllPskOrder_currentIndexChanged(), on_rrcFilter_toggled(), on_rrcRolloff_valueChanged(), on_signalSelect_currentIndexChanged(), on_spanLog2_currentIndexChanged(), on_ssb_toggled(), on_useRationalDownsampler_toggled(), onMenuDialogCalled(), resetToDefaults(), serialize(), setCenterFrequency(), setNewFinalRate(), and setSpectrumDisplay().
m_spectrumScopeComboVis
SpectrumScopeComboVis* ChannelAnalyzerGUI::m_spectrumScopeComboVis private
Definition at line 75 of file chanalyzergui.h.
Referenced by ChannelAnalyzerGUI(), and ~ChannelAnalyzerGUI().
m_spectrumVis
SpectrumVis* ChannelAnalyzerGUI::m_spectrumVis private
Definition at line 76 of file chanalyzergui.h.
Referenced by ChannelAnalyzerGUI(), and ~ChannelAnalyzerGUI().
ui
Ui::ChannelAnalyzerGUI* ChannelAnalyzerGUI::ui private
Definition at line 65 of file chanalyzergui.h.
Referenced by blockApplySettings(), ChannelAnalyzerGUI(), channelMarkerChangedByCursor(), displayPLLSettings(), displaySettings(), getRequestedChannelSampleRate(), handleMessage(), on_BW_valueChanged(), on_lowCut_valueChanged(), on_pll_toggled(), on_rrcRolloff_valueChanged(), on_ssb_toggled(), setFiltersUIBoundaries(), setNewFinalRate(), setSpectrumDisplay(), tick(), and ~ChannelAnalyzerGUI().
The documentation for this class was generated from the following files:
plugins/channelrx/chanalyzer/chanalyzergui.h
plugins/channelrx/chanalyzer/chanalyzergui.cpp