SDRAngel: MainWindow::MsgSetDevice Class Reference
MainWindow::MsgSetDevice Class Reference
Public Member Functions
int getDeviceSetIndex () const
int getDeviceIndex () const
int getDeviceType () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgSetDevice * create (int deviceSetIndex, int deviceIndex, bool tx)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgSetDevice (int deviceSetIndex, int deviceIndex, int deviceType)
Private Attributes
int m_deviceSetIndex
int m_deviceIndex
int m_deviceType
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 194 of file mainwindow.h.
Constructor & Destructor Documentation
MsgSetDevice()
MainWindow::MsgSetDevice::MsgSetDevice (int deviceSetIndex, int deviceIndex, int deviceType) inline private
Definition at line 212 of file mainwindow.h.
                                                                           :
             Message(),
             m_deviceSetIndex(deviceSetIndex),
             m_deviceIndex(deviceIndex),
             m_deviceType(deviceType)
         { }
Member Function Documentation
create()
static MsgSetDevice* MainWindow::MsgSetDevice::create (int deviceSetIndex, int deviceIndex, bool tx) inline static
Definition at line 202 of file mainwindow.h.
Referenced by WebAPIAdapterGUI::devicesetDevicePut().
         {
             return new MsgSetDevice(deviceSetIndex, deviceIndex, tx);
         }
getDeviceIndex()
int MainWindow::MsgSetDevice::getDeviceIndex () const inline
Definition at line 199 of file mainwindow.h.
Referenced by MainWindow::handleMessage().
 { return m_deviceIndex; }
getDeviceSetIndex()
int MainWindow::MsgSetDevice::getDeviceSetIndex () const inline
Definition at line 198 of file mainwindow.h.
Referenced by MainWindow::handleMessage().
 { return m_deviceSetIndex; }
getDeviceType()
int MainWindow::MsgSetDevice::getDeviceType () const inline
Definition at line 200 of file mainwindow.h.
Referenced by MainWindow::handleMessage().
 { return m_deviceType; }
Member Data Documentation
m_deviceIndex
int MainWindow::MsgSetDevice::m_deviceIndex private
Definition at line 209 of file mainwindow.h.
m_deviceSetIndex
int MainWindow::MsgSetDevice::m_deviceSetIndex private
Definition at line 208 of file mainwindow.h.
m_deviceType
int MainWindow::MsgSetDevice::m_deviceType private
Definition at line 210 of file mainwindow.h.
The documentation for this class was generated from the following file:
sdrgui/mainwindow.h