SDRAngel: ArgInfoGUI Class Reference
ArgInfoGUI Class Reference
#include <arginfogui.h>
Inherits QWidget.
Public Types
enum ArgInfoType { ArgInfoBinary, ArgInfoContinuous, ArgInfoDiscrete }
enum ArgInfoValueType { ArgInfoValueBool, ArgInfoValueInt, ArgInfoValueFloat, ArgInfoValueString }
Signals
void valueChanged ()
Public Member Functions
ArgInfoGUI (ArgInfoType type, ArgInfoValueType valueType, QWidget *parent=0)
~ArgInfoGUI ()
void setLabel (const QString &text)
void setToolTip (const QString &text)
void setUnits (const QString &units)
ArgInfoType getType () const
ArgInfoValueType getValueType () const
void setRange (double min, double max)
bool getBoolValue () const
void setBoolValue (bool value)
void addBoolValue (const QString &text, bool value)
int getIntValue () const
void setIntValue (int value)
void addIntValue (const QString &text, int value)
double getFloatValue () const
void setFloatValue (double value)
void addFloatValue (const QString &text, double value)
const QString & getStringValue () const
void setStringValue (const QString &value)
void addStringValue (const QString &text, const QString &value)
Private Slots
void on_argCheck_toggled (bool checked)
void on_argEdit_editingFinished ()
void on_argCombo_currentIndexChanged (int index)
Private Member Functions
int setIntegerValue (int value)
double setDoubleValue (double value)
void updateUIFromBool ()
void updateUIFromInt ()
void updateUIFromFloat ()
void updateUIFromString ()
Private Attributes
Ui::ArgInfoGUI * ui
ArgInfoType m_type
ArgInfoValueType m_valueType
bool m_boolValue
int m_intValue
double m_floatValue
QString m_stringValue
bool m_hasRange
double m_minValue
double m_maxValue
Detailed Description
Definition at line 30 of file arginfogui.h.
Member Enumeration Documentation
ArgInfoType
enum ArgInfoGUI::ArgInfoType
Enumerator
ArgInfoBinary
ArgInfoContinuous
ArgInfoDiscrete
Definition at line 34 of file arginfogui.h.
     {
         ArgInfoBinary,
         ArgInfoContinuous,
         ArgInfoDiscrete
     };
ArgInfoValueType
enum ArgInfoGUI::ArgInfoValueType
Enumerator
ArgInfoValueBool
ArgInfoValueInt
ArgInfoValueFloat
ArgInfoValueString
Definition at line 41 of file arginfogui.h.
     {
         ArgInfoValueBool,
         ArgInfoValueInt,
         ArgInfoValueFloat,
         ArgInfoValueString
     };
Constructor & Destructor Documentation
ArgInfoGUI()
ArgInfoGUI::ArgInfoGUI (ArgInfoType type, ArgInfoValueType valueType, QWidget * parent = 0) explicit
Definition at line 24 of file arginfogui.cpp.
References ArgInfoBinary, ArgInfoContinuous, ArgInfoDiscrete, ArgInfoValueFloat, ArgInfoValueInt, m_type, m_valueType, and ui.
                                                                                     :
     QWidget(parent),
     ui(new Ui::ArgInfoGUI),
     m_type(type),
     m_valueType(valueType),
     m_boolValue(false),
     m_intValue(0),
     m_floatValue(0.0),
     m_hasRange(false),
     m_minValue(0.0),
     m_maxValue(0.0)
 {
     ui->setupUi(this);
     QHBoxLayout *layout = ui->argLayout;
     if ((m_valueType == ArgInfoValueInt) || (m_valueType == ArgInfoValueFloat))
     {
         if (m_type == ArgInfoContinuous) {
             ui->argEdit->setAlignment(Qt::AlignRight);
         } else if (m_type == ArgInfoDiscrete) {
             ui->argCombo->setLayoutDirection(Qt::RightToLeft);
         }
     }
     if (m_type != ArgInfoBinary)
     {
         layout->removeWidget(ui->argCheck);
         delete ui->argCheck;
     }
     if (m_type != ArgInfoContinuous)
     {
         layout->removeWidget(ui->argEdit);
         delete ui->argEdit;
     }
     if (m_type != ArgInfoDiscrete)
     {
         layout->removeWidget(ui->argCombo);
         delete ui->argCombo;
     }
 }
~ArgInfoGUI()
ArgInfoGUI::~ArgInfoGUI ()
Definition at line 67 of file arginfogui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
addBoolValue()
void ArgInfoGUI::addBoolValue (const QString & text, bool value)
Definition at line 124 of file arginfogui.cpp.
References ArgInfoDiscrete, m_type, and ui.
 {
     if (m_type == ArgInfoDiscrete) {
         ui->argCombo->addItem(text, QVariant(value));
     }
 }
addFloatValue()
void ArgInfoGUI::addFloatValue (const QString & text, double value)
Definition at line 186 of file arginfogui.cpp.
References ArgInfoDiscrete, m_type, setDoubleValue(), and ui.
Referenced by SoapySDRInputGui::createArgumentsControl(), and SoapySDROutputGui::createArgumentsControl().
 {
     if (m_type == ArgInfoDiscrete) {
         ui->argCombo->addItem(text, QVariant(setDoubleValue(value)));
     }
 }
addIntValue()
void ArgInfoGUI::addIntValue (const QString & text, int value)
Definition at line 155 of file arginfogui.cpp.
References ArgInfoDiscrete, m_type, setIntegerValue(), and ui.
Referenced by SoapySDRInputGui::createArgumentsControl(), and SoapySDROutputGui::createArgumentsControl().
 {
     if (m_type == ArgInfoDiscrete) {
         ui->argCombo->addItem(text, QVariant(setIntegerValue(value)));
     }
 }
addStringValue()
void ArgInfoGUI::addStringValue (const QString & text, const QString & value)
Definition at line 219 of file arginfogui.cpp.
References ArgInfoDiscrete, m_type, and ui.
Referenced by SoapySDRInputGui::createArgumentsControl(), and SoapySDROutputGui::createArgumentsControl().
 {
     if (m_type == ArgInfoDiscrete) {
         ui->argCombo->addItem(text, QVariant(value));
     }
 }
getBoolValue()
bool ArgInfoGUI::getBoolValue () const inline
Definition at line 60 of file arginfogui.h.
Referenced by DynamicArgSettingGUI::getValue(), and DynamicArgSettingGUI::processValueChanged().
 { return m_boolValue; }
getFloatValue()
double ArgInfoGUI::getFloatValue () const inline
Definition at line 68 of file arginfogui.h.
Referenced by DynamicArgSettingGUI::getValue(), and DynamicArgSettingGUI::processValueChanged().
 { return m_floatValue; }
getIntValue()
int ArgInfoGUI::getIntValue () const inline
Definition at line 64 of file arginfogui.h.
Referenced by DynamicArgSettingGUI::getValue(), and DynamicArgSettingGUI::processValueChanged().
 { return m_intValue; }
getStringValue()
const QString& ArgInfoGUI::getStringValue () const inline
Definition at line 72 of file arginfogui.h.
Referenced by DynamicArgSettingGUI::getValue(), and DynamicArgSettingGUI::processValueChanged().
 { return m_stringValue; }
getType()
ArgInfoType ArgInfoGUI::getType () const inline
Definition at line 56 of file arginfogui.h.
 { return m_type; }
getValueType()
ArgInfoValueType ArgInfoGUI::getValueType () const inline
Definition at line 57 of file arginfogui.h.
References leansdr::max(), and leansdr::min().
Referenced by DynamicArgSettingGUI::getValue(), and DynamicArgSettingGUI::processValueChanged().
 { return m_valueType; }
on_argCheck_toggled
void ArgInfoGUI::on_argCheck_toggled (bool checked) private slot
Definition at line 373 of file arginfogui.cpp.
References setBoolValue(), and valueChanged().
 {
     setBoolValue(checked);
     emit valueChanged();
 }
on_argCombo_currentIndexChanged
void ArgInfoGUI::on_argCombo_currentIndexChanged (int index) private slot
Definition at line 385 of file arginfogui.cpp.
References setBoolValue(), setFloatValue(), setIntValue(), setStringValue(), ui, and valueChanged().
 {
     (void) index;
     QVariant v = ui->argCombo->currentData();
     bool ok = false;
     if (v.type() == QVariant::Bool)
     {
         setBoolValue(v.toBool());
         emit valueChanged();
     }
     else if (v.type() == QVariant::Int)
     {
         setIntValue(v.toInt(&ok));
         if (ok) {
             emit valueChanged();
         }
     }
     else if (v.type() == QVariant::Double)
     {
         setFloatValue(v.toDouble(&ok));
         if (ok) {
             emit valueChanged();
         }
     }
     else if (v.type() ==QVariant::String)
     {
         setStringValue(v.toString());
         emit valueChanged();
     }
 }
on_argEdit_editingFinished
void ArgInfoGUI::on_argEdit_editingFinished () private slot
Definition at line 379 of file arginfogui.cpp.
References setStringValue(), ui, and valueChanged().
 {
     setStringValue(ui->argEdit->text());
     emit valueChanged();
 }
setBoolValue()
void ArgInfoGUI::setBoolValue (bool value)
Definition at line 100 of file arginfogui.cpp.
References ArgInfoValueBool, ArgInfoValueFloat, ArgInfoValueInt, ArgInfoValueString, m_boolValue, m_floatValue, m_intValue, m_stringValue, m_valueType, setDoubleValue(), setIntegerValue(), updateUIFromBool(), updateUIFromFloat(), updateUIFromInt(), and updateUIFromString().
Referenced by on_argCheck_toggled(), on_argCombo_currentIndexChanged(), and DynamicArgSettingGUI::setValue().
 {
     if (m_valueType == ArgInfoValueBool)
     {
         m_boolValue = value;
         updateUIFromBool();
     }
     else if (m_valueType == ArgInfoValueInt)
     {
         m_intValue = setIntegerValue(value ? 1 : 0);
         updateUIFromInt();
     }
     else if (m_valueType == ArgInfoValueFloat)
     {
         m_floatValue = setDoubleValue(value ? 1.0 : 0.0);
         updateUIFromFloat();
     }
     else if (m_valueType == ArgInfoValueString)
     {
         m_stringValue = QString(value ? "true" : "false");
         updateUIFromString();
     }
 }
setDoubleValue()
double ArgInfoGUI::setDoubleValue (double value) private
Definition at line 235 of file arginfogui.cpp.
References m_hasRange, and m_maxValue.
Referenced by addFloatValue(), setBoolValue(), setFloatValue(), setIntValue(), and setStringValue().
 {
     if (m_hasRange) {
         return value < m_minValue ? m_minValue : value > m_maxValue ? m_maxValue : value;
     } else {
         return value;
     }
 }
setFloatValue()
void ArgInfoGUI::setFloatValue (double value)
Definition at line 162 of file arginfogui.cpp.
References ArgInfoValueBool, ArgInfoValueFloat, ArgInfoValueInt, ArgInfoValueString, m_boolValue, m_floatValue, m_intValue, m_stringValue, m_valueType, setDoubleValue(), setIntegerValue(), updateUIFromBool(), updateUIFromFloat(), updateUIFromInt(), and updateUIFromString().
Referenced by on_argCombo_currentIndexChanged(), and DynamicArgSettingGUI::setValue().
 {
     if (m_valueType == ArgInfoValueBool)
     {
         m_boolValue = (value != 0.0);
         updateUIFromBool();
     }
     else if (m_valueType == ArgInfoValueInt)
     {
         m_intValue = setIntegerValue(value);
         updateUIFromInt();
     }
     else if (m_valueType == ArgInfoValueFloat)
     {
         m_floatValue = setDoubleValue(value);
         updateUIFromFloat();
     }
     else if (m_valueType == ArgInfoValueString)
     {
         m_stringValue = QString("%1").arg(value);
         updateUIFromString();
     }
 }
setIntegerValue()
int ArgInfoGUI::setIntegerValue (int value) private
Definition at line 226 of file arginfogui.cpp.
References m_hasRange, and m_maxValue.
Referenced by addIntValue(), setBoolValue(), setFloatValue(), setIntValue(), and setStringValue().
 {
     if (m_hasRange) {
         return value < round(m_minValue) ? round(m_minValue) : value > round(m_maxValue) ? round(m_maxValue) : value;
     } else {
         return value;
     }
 }
setIntValue()
void ArgInfoGUI::setIntValue (int value)
Definition at line 131 of file arginfogui.cpp.
References ArgInfoValueBool, ArgInfoValueFloat, ArgInfoValueInt, ArgInfoValueString, m_boolValue, m_floatValue, m_intValue, m_stringValue, m_valueType, setDoubleValue(), setIntegerValue(), updateUIFromBool(), updateUIFromFloat(), updateUIFromInt(), and updateUIFromString().
Referenced by on_argCombo_currentIndexChanged(), and DynamicArgSettingGUI::setValue().
 {
     if (m_valueType == ArgInfoValueBool)
     {
         m_boolValue = (value != 0);
         updateUIFromBool();
     }
     else if (m_valueType == ArgInfoValueInt)
     {
         m_intValue = setIntegerValue(value);
         updateUIFromInt();
     }
     else if (m_valueType == ArgInfoValueFloat)
     {
         m_floatValue = setDoubleValue(value);
         updateUIFromFloat();
     }
     else if (m_valueType == ArgInfoValueString)
     {
         m_stringValue = QString("%1").arg(value);
         updateUIFromString();
     }
 }
setLabel()
void ArgInfoGUI::setLabel (const QString & text)
Definition at line 79 of file arginfogui.cpp.
References ui.
Referenced by SoapySDRInputGui::createArgumentsControl(), and SoapySDROutputGui::createArgumentsControl().
 {
     ui->argLabel->setText(text);
 }
setRange()
void ArgInfoGUI::setRange (double min, double max)
Definition at line 72 of file arginfogui.cpp.
References m_hasRange, m_maxValue, m_minValue, leansdr::max(), and leansdr::min().
Referenced by SoapySDRInputGui::createArgumentsControl(), and SoapySDROutputGui::createArgumentsControl().
 {
     m_hasRange = true;
     m_minValue = min;
     m_maxValue = max;
 }
setStringValue()
void ArgInfoGUI::setStringValue (const QString & value)
Definition at line 193 of file arginfogui.cpp.
References ArgInfoValueBool, ArgInfoValueFloat, ArgInfoValueInt, ArgInfoValueString, m_boolValue, m_floatValue, m_intValue, m_stringValue, m_valueType, setDoubleValue(), setIntegerValue(), updateUIFromBool(), updateUIFromFloat(), updateUIFromInt(), and updateUIFromString().
Referenced by on_argCombo_currentIndexChanged(), on_argEdit_editingFinished(), and DynamicArgSettingGUI::setValue().
 {
     if (m_valueType == ArgInfoValueBool)
     {
         m_boolValue = (value == "true");
         updateUIFromBool();
     }
     else if (m_valueType == ArgInfoValueInt)
     {
         int intValue = atoi(value.toStdString().c_str());
         m_intValue = setIntegerValue(intValue);
         updateUIFromInt();
     }
     else if (m_valueType == ArgInfoValueFloat)
     {
         double doubleValue = atof(value.toStdString().c_str());
         m_floatValue = setDoubleValue(doubleValue);
         updateUIFromFloat();
     }
     else if (m_valueType == ArgInfoValueString)
     {
         m_stringValue = value;
         updateUIFromString();
     }
 }
setToolTip()
void ArgInfoGUI::setToolTip (const QString & text)
Definition at line 84 of file arginfogui.cpp.
References ArgInfoBinary, ArgInfoContinuous, ArgInfoDiscrete, m_type, and ui.
Referenced by SoapySDRInputGui::createArgumentsControl(), and SoapySDROutputGui::createArgumentsControl().
 {
     if (m_type == ArgInfoBinary) {
         ui->argCheck->setToolTip(text);
     } else if (m_type == ArgInfoContinuous) {
         ui->argEdit->setToolTip(text);
     } else if (m_type == ArgInfoDiscrete) {
         ui->argCombo->setToolTip(text);
     }
 }
setUnits()
void ArgInfoGUI::setUnits (const QString & units)
Definition at line 95 of file arginfogui.cpp.
References ui.
Referenced by SoapySDRInputGui::createArgumentsControl(), and SoapySDROutputGui::createArgumentsControl().
 {
     ui->argUnits->setText(units);
 }
updateUIFromBool()
void ArgInfoGUI::updateUIFromBool () private
Definition at line 244 of file arginfogui.cpp.
References ArgInfoBinary, ArgInfoContinuous, ArgInfoDiscrete, m_boolValue, m_type, and ui.
Referenced by setBoolValue(), setFloatValue(), setIntValue(), and setStringValue().
 {
     if (m_type == ArgInfoBinary)
     {
         ui->argCheck->blockSignals(true);
         ui->argCheck->setChecked(m_boolValue);
         ui->argCheck->blockSignals(false);
     }
     else if (m_type == ArgInfoContinuous)
     {
         ui->argEdit->blockSignals(true);
         ui->argEdit->setText(QString(m_boolValue ? "true" : "false"));
         ui->argEdit->blockSignals(false);
     }
     else if (m_type == ArgInfoDiscrete)
     {
         if (ui->argCombo->count() > 1)
         {
             ui->argCombo->blockSignals(true);
             ui->argCombo->setCurrentIndex(m_boolValue ? 0 : 1);
             ui->argCombo->blockSignals(false);
         }
     }
 }
updateUIFromFloat()
void ArgInfoGUI::updateUIFromFloat () private
Definition at line 304 of file arginfogui.cpp.
References arg(), ArgInfoBinary, ArgInfoContinuous, ArgInfoDiscrete, i, m_floatValue, m_type, and ui.
Referenced by setBoolValue(), setFloatValue(), setIntValue(), and setStringValue().
 {
     if (m_type == ArgInfoBinary)
     {
         ui->argCheck->blockSignals(true);
         ui->argCheck->setChecked(m_floatValue == 0.0 ? false : true);
         ui->argCheck->blockSignals(false);
     }
     else if (m_type == ArgInfoContinuous)
     {
         ui->argEdit->blockSignals(true);
         ui->argEdit->setText(QString("%1").arg(m_floatValue));
         ui->argEdit->blockSignals(false);
     }
     else if (m_type == ArgInfoDiscrete)
     {
         for (int i = 0; i < ui->argCombo->count(); i++)
         {
             if (ui->argCombo->itemData(i).type() == QVariant::Double)
             {
                 bool ok = false;
                 QVariant v = ui->argCombo->itemData(i);
                 if (m_floatValue >= v.toDouble(&ok) && ok)
                 {
                     ui->argCombo->blockSignals(true);
                     ui->argCombo->setCurrentIndex(i);
                     ui->argCombo->blockSignals(false);
                     break;
                 }
             }
         }
     }
 }
updateUIFromInt()
void ArgInfoGUI::updateUIFromInt () private
Definition at line 269 of file arginfogui.cpp.
References arg(), ArgInfoBinary, ArgInfoContinuous, ArgInfoDiscrete, i, m_intValue, m_type, and ui.
Referenced by setBoolValue(), setFloatValue(), setIntValue(), and setStringValue().
 {
     if (m_type == ArgInfoBinary)
     {
         ui->argCheck->blockSignals(true);
         ui->argCheck->setChecked(m_intValue == 0 ? false : true);
         ui->argCheck->blockSignals(false);
     }
     else if (m_type == ArgInfoContinuous)
     {
         ui->argEdit->blockSignals(true);
         ui->argEdit->setText(QString("%1").arg(m_intValue));
         ui->argEdit->blockSignals(false);
     }
     else if (m_type == ArgInfoDiscrete)
     {
         for (int i = 0; i < ui->argCombo->count(); i++)
         {
             if (ui->argCombo->itemData(i).type() == QVariant::Int)
             {
                 bool ok = false;
                 QVariant v = ui->argCombo->itemData(i);
                 if (m_intValue >= v.toInt(&ok) && ok)
                 {
                     ui->argCombo->blockSignals(true);
                     ui->argCombo->setCurrentIndex(i);
                     ui->argCombo->blockSignals(false);
                     break;
                 }
             }
         }
     }
 }
updateUIFromString()
void ArgInfoGUI::updateUIFromString () private
Definition at line 339 of file arginfogui.cpp.
References ArgInfoBinary, ArgInfoContinuous, ArgInfoDiscrete, i, m_stringValue, m_type, and ui.
Referenced by setBoolValue(), setFloatValue(), setIntValue(), and setStringValue().
 {
     if (m_type == ArgInfoBinary)
     {
         ui->argCheck->blockSignals(true);
         ui->argCheck->setChecked(m_stringValue == "true" ? true : false);
         ui->argCheck->blockSignals(false);
     }
     else if (m_type == ArgInfoContinuous)
     {
         ui->argEdit->blockSignals(true);
         ui->argEdit->setText(m_stringValue);
         ui->argEdit->blockSignals(false);
     }
     else if (m_type == ArgInfoDiscrete)
     {
         for (int i = 0; i < ui->argCombo->count(); i++)
         {
             if (ui->argCombo->itemData(i).type() == QVariant::String)
             {
                 QVariant v = ui->argCombo->itemData(i);
                 if (m_stringValue == v.toString())
                 {
                     ui->argCombo->blockSignals(true);
                     ui->argCombo->setCurrentIndex(i);
                     ui->argCombo->blockSignals(false);
                     break;
                 }
             }
         }
     }
 }
valueChanged
void ArgInfoGUI::valueChanged () signal
Referenced by on_argCheck_toggled(), on_argCombo_currentIndexChanged(), and on_argEdit_editingFinished().
Member Data Documentation
m_boolValue
bool ArgInfoGUI::m_boolValue private
Definition at line 95 of file arginfogui.h.
Referenced by setBoolValue(), setFloatValue(), setIntValue(), setStringValue(), and updateUIFromBool().
m_floatValue
double ArgInfoGUI::m_floatValue private
Definition at line 97 of file arginfogui.h.
Referenced by setBoolValue(), setFloatValue(), setIntValue(), setStringValue(), and updateUIFromFloat().
m_hasRange
bool ArgInfoGUI::m_hasRange private
Definition at line 99 of file arginfogui.h.
Referenced by setDoubleValue(), setIntegerValue(), and setRange().
m_intValue
int ArgInfoGUI::m_intValue private
Definition at line 96 of file arginfogui.h.
Referenced by setBoolValue(), setFloatValue(), setIntValue(), setStringValue(), and updateUIFromInt().
m_maxValue
double ArgInfoGUI::m_maxValue private
Definition at line 101 of file arginfogui.h.
Referenced by setDoubleValue(), setIntegerValue(), and setRange().
m_minValue
double ArgInfoGUI::m_minValue private
Definition at line 100 of file arginfogui.h.
Referenced by setRange().
m_stringValue
QString ArgInfoGUI::m_stringValue private
Definition at line 98 of file arginfogui.h.
Referenced by setBoolValue(), setFloatValue(), setIntValue(), setStringValue(), and updateUIFromString().
m_type
ArgInfoType ArgInfoGUI::m_type private
Definition at line 93 of file arginfogui.h.
Referenced by addBoolValue(), addFloatValue(), addIntValue(), addStringValue(), ArgInfoGUI(), setToolTip(), updateUIFromBool(), updateUIFromFloat(), updateUIFromInt(), and updateUIFromString().
m_valueType
ArgInfoValueType ArgInfoGUI::m_valueType private
Definition at line 94 of file arginfogui.h.
Referenced by ArgInfoGUI(), setBoolValue(), setFloatValue(), setIntValue(), and setStringValue().
ui
Ui::ArgInfoGUI* ArgInfoGUI::ui private
Definition at line 92 of file arginfogui.h.
Referenced by addBoolValue(), addFloatValue(), addIntValue(), addStringValue(), ArgInfoGUI(), on_argCombo_currentIndexChanged(), on_argEdit_editingFinished(), setLabel(), setToolTip(), setUnits(), updateUIFromBool(), updateUIFromFloat(), updateUIFromInt(), updateUIFromString(), and ~ArgInfoGUI().
The documentation for this class was generated from the following files:
sdrgui/soapygui/arginfogui.h
sdrgui/soapygui/arginfogui.cpp